name: Pull request
on:
  pull_request:
    branches:
      - develop
      - main
jobs:
  actions:
    runs-on: ubuntu-latest
    steps:
    - name: Copia repositorio
      uses: actions/checkout@v2
    - name: Construye imagen
      run: docker build --tag islasgeci/ctf .
    - name: Verifica el formato
      run: docker run islasgeci/ctf make check
    - name: Corre pruebas
      run: docker run islasgeci/ctf make init
    - name: Evalúa resistencia a mutaciones
      run: docker run islasgeci/ctf make mutants
